#!/bin/sh
# This code is generated by "karabiner export"

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set parameter.simultaneouskeypresses_pointingbutton_delay 20
/bin/echo -n .
$cli set repeat.initial_wait 200
/bin/echo -n .
$cli set parameter.simultaneouskeypresses_delay 20
/bin/echo -n .
$cli set parameter.doublepressmodifier_threshold 100
/bin/echo -n .
$cli set repeat.consumer_initial_wait 50
/bin/echo -n .
$cli set repeat.wait 30
/bin/echo -n .
$cli set repeat.consumer_wait 50
/bin/echo -n .
$cli set repeat.keyoverlaidmodifier_initial_wait 200
/bin/echo -n .
$cli set parameter.keyoverlaidmodifier_timeout 500
/bin/echo -n .
$cli set parameter.holdingkeytokey_wait 150
/bin/echo -n .
$cli set pointing.relative2scroll_rate 50
/bin/echo -n .
/bin/echo
