#!/bin/sh
# This code is generated by "karabiner export"

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set repeat.wait 20
/bin/echo -n .
$cli set repeat.initial_wait 200
/bin/echo -n .
$cli set repeat.consumer_initial_wait 50
/bin/echo -n .
$cli set repeat.consumer_wait 50
/bin/echo -n .
/bin/echo
